"""Compact assets/music/bed-audio.json into assets/music/bed-audio.js.

The composition only needs three derived signals per frame (bass, mid, rms),
not the raw 16-band matrix, so the shipped file stays small enough to inline
without bloating index.html. Deterministic: no clocks, no randomness.
"""

import json
import pathlib

HERE = pathlib.Path(__file__).resolve().parent
COMPOSITION = HERE.parent
SRC = COMPOSITION / "assets" / "music" / "bed-audio.json"
DST = COMPOSITION / "assets" / "music" / "bed-audio.js"

data = json.loads(SRC.read_text(encoding="utf-8"))
frames = data["frames"]

bass, mid, rms = [], [], []
for f in frames:
    b = f["bands"]
    bass.append(round(b[0], 3))
    mid.append(round(sum(b[4:9]) / 5.0, 3))
    rms.append(f["rms"])


def pack(values):
    return "[" + ",".join(str(v) for v in values) + "]"


out = (
    "/* Generated by scripts/build-audio-js.py from bed-audio.json. Do not edit. */\n"
    "window.BED_AUDIO = {\n"
    f"  fps: {data['fps']},\n"
    f"  totalFrames: {data['totalFrames']},\n"
    f"  bass: {pack(bass)},\n"
    f"  mid: {pack(mid)},\n"
    f"  rms: {pack(rms)}\n"
    "};\n"
)
DST.write_text(out, encoding="utf-8")
print(f"wrote {DST.name} ({len(out)} bytes, {len(frames)} frames)")