import { useState } from 'react';
import { Calculator, ArrowUpRight } from 'lucide-react';
import { estimateChannels, money } from '../../services/draft';
export default function WhatIfSimulator({ draft, customers }) {
    const [values, setValues] = useState({ budget: 5000, customers: customers || 0, price: Number(draft.price) || 1000, cost: 600, conversion: 5, fee: 15, target: 10000 });
    const rows = estimateChannels(values);
    const peak = Math.max(...rows.map(r => Math.abs(r.profit)), 1);
    const fields = [['budget', 'Campaign budget (₹)', 1000, 30000, 500], ['customers', 'Opted-in customers', 0, 1000, 1], ['price', 'Selling price (₹)', 100, 10000, 100], ['cost', 'Cost per item (₹)', 0, 10000, 100], ['conversion', 'Customer conversion (%)', 1, 30, 1], ['fee', 'Marketplace fee assumption (%)', 0, 35, 0.5], ['target', 'Sales target (₹)', 1000, 100000, 1000]];
    return <div className="stack"><p className="notice"><Calculator size={17}/> Illustrative scenarios, not forecasts. All rates are editable demo assumptions; tax, shipping and returns are excluded.</p><div className="planner-layout"><section className="surface planner-inputs"><h2>Your starting point</h2>{fields.map(([key, label, min, max, step]) => <label className="planner-field" key={key}><span>{label}</span><input className="field" type="number" min={min} max={max} step={step} value={values[key]} onChange={e => setValues(v => ({ ...v, [key]: Math.max(0, Math.min(max, Number(e.target.value) || 0)) }))}/></label>)}</section><section className="surface planner-chart"><p className="eyebrow">COMPARE THE POSSIBILITIES</p><h2>Estimated contribution after campaign costs</h2><p className="meta">Revenue minus product cost, campaign spend and the fee assumption.</p>{rows.map(r => <div className="chart-row" key={r.name}><div><strong>{r.name}</strong><span className={r.profit < 0 ? 'negative' : ''}>{money(r.profit)}</span></div><div className="chart-track"><div style={{ width: `${Math.abs(r.profit) / peak * 100}%`, background: r.profit < 0 ? 'var(--stop)' : r.recommended ? 'var(--accent)' : 'var(--ok)' }}/></div><p>{r.orders} assumed orders · {money(r.revenue)} sales · {r.affordable ? 'Within campaign budget' : 'Over campaign budget'}</p>{r.recommended && <span className="pill pill-accent"><ArrowUpRight size={13}/>Best eligible result under these assumptions</span>}</div>)}<p className="meta">Target: {money(values.target)}. {rows.some(r => r.affordable && r.reachesTarget) ? 'At least one scenario reaches it.' : 'No affordable scenario reaches it; change your assumptions or target.'}</p></section></div><details className="model-notes"><summary>How these scenarios are calculated</summary><p>Customer campaign: customers × conversion, rounded down; ₹1 assumed message cost per customer. Marketplace: budget ÷ price × 2 assumed orders, rounded down. Local ads: budget ÷ price × 1.6 assumed orders, rounded down. Campaign spend is deducted in full. These multipliers are illustrative, not measured performance.</p><p>Recommendations consider affordable scenarios with positive contribution. Those meeting your sales target are preferred, then the highest contribution wins. No positive affordable result means no recommendation.</p></details></div>;
}
